
# Если вы испытываете проблемы с плагином, то эта функция облегчит поиск проблемы
debug: false

AutoStart:
  # Минимальный онлайн для того чтобы запустился ивент, если Freeze включён то таймер будет заморожен если онлайн ниже этого
  minPlayers: 3
  # Если true, то таймер заморозится если недостаточно игроков
  # Если false, то таймер будет продолжать идти ни смотря на онлайн
  Freeze: true
  # TIMER - Каждое time будет начинаться ивент
  # TIMEZONE - Запускать ивент чётко по расписанию из zones
  type: TIMER
  # Если ";$rand_group", то рандомный ивент из рандомной группы. Например: time: 3600;$rand_group
  # если ничего не добавлять то будет выбран рандомный ивент
  time: 1800

  # Нужно только если в type стоит TIMEZONE
  zone: GMT+3
  times:
    - '10:00;id' # если добавить ";id_ивента", то в это время будет именно данный ивент
    - '13:00;group_id' # если добавить ";group_id", то в это время будет случайный ивент из этой группы
    - '15:00;$rand_group' # если $rand_group, то рандомный ивент из рандомной группы
    - '21:00' # если же ничего не добавлять, то будет просто рандомный ивент
    - '23:00'
    - '17:00:SUNDAY' # да, можно даже поставить даже дни недели



Groups:
  group-1:
    # Если выбирается рандомная группа, то это шанс того что выпадет группа
    Chance: 50
    # Выбирается случайный ивент из списка с учётом его шанса и минимального онлайна
    Events:
      - example

Events:
  example:
    # Вы можете делать шанс спавна ивента, однако если вы ни в одном ивент не поставите шанс то всё будет ок ибо выбран будет случайный ивент
    # Если же во всех ивентах будет свой шанс то выберется случайный ивент с шансом
    Chance: 100
    Duration: 300 # В секундах. Время через которое ивент закончится
    Prefix: "&dМистический сундук"
    # Если не будете пользоваться компасом, тогда удалите строки compass и coordinates

    compass: true
    coordinates:
      world: "%placeholder_world%" # замените %placeholder_world% на свой плейсхолдер для получения координат
      x: "%placeholder_x%"
      y: "%placeholder_y%"
      z: "%placeholder_z%"

    ActivationTime: 60 # В секундах. Через какое время ивент будет открыт. Эта функция подходит для мистиков как на FunTime. Если вам это не нужно тогда уберите эту строку

    activeInfo: # Отображается в /event info
      - ""
      - "{prefix}"
      - "Координаты: %placeholder_x% %placeholder_y% %placeholder_z%"
      - "Редкость: &5Эпический"
      - "Статус: {active_status}"
      - "До завершения: {duration} секунд"
      - ""

    warns:
      time:
        - 300
        - 120
        - 30
      warnActions:
        - "[MESSAGE] "
        - "[MESSAGE] %eventdelay_prefix%"
        - "[MESSAGE] Редкость: &5Эпический"
        - "[MESSAGE] Ивент начнётся через &6%eventdelay_time_to_start%"
        - "[MESSAGE] "

    onStart: # Команды на запуск ивента
      default:
        - "[CONSOLE] bair start epic"
        - "[SEND_WEBHOOK] example"
      random:
        random-1:
          - "[CONSOLE] bair start epic2"
        random-2:
          - "[CONSOLE] bair start epic3"
    # Команды если была прописана команда /event activate
    onActivated: { }
    onEnd:
      - "[MESSAGE] Конец ивента %eventdelay_prefix%"
